#! /usr/bin/env php

<?php
    use Acme\ShowCommand;
    use Symfony\Component\Console\Application;
    
    

    require 'vendor/autoload.php';

    $app=new Application('MoviePedia Demo','1.0');
    $app->add(new ShowCommand(new GuzzleHttp\Client));
    $app->run();


?>

